syntax = "proto3";

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

option go_package = "./generated";

// Represents an item in a gallery option (e.g., a color option with images).
message GalleryOption {
  string value = 1; // Value of the option (e.g., "blue", "medium")
  repeated string image_urls = 2; // List of associated image URLs
}

// Represents a gallery option with multiple options.
message GalleryOptions {
  string name = 1; // Name of the option (e.g., "color")
  repeated GalleryOption options = 2; // List of options
}

// Represents a regular option (e.g., size or material).
message Option {
  string name = 1; // Name of the option (e.g., "size")
  repeated string options = 2; // List of options
}

message Options {
  repeated Option options = 1;
}

// Represents a product.
message Product {
  string name = 1; // Name of the product
  string thumbnail_url = 2; // URL of the thumbnail image
  string category_name = 3; // Name of the category
  string description= 4; // Product description
  uint32 cent_price = 5; // Price in cents (e.g., 5000 for $50.00)
  bool in_stock = 6; // Availability status
  float rating = 7; // Product rating (e.g., 4.5)
  uint32 amount_sold = 8; // Number of units sold
  GalleryOption gallery_option = 9; // Gallery option (e.g., color with images)
  Options options = 10; // option list (e.g., size, material)
  google.protobuf.Struct attributes = 11; // size chart, material, etc. 
  google.protobuf.Timestamp created_at = 12; // Database timestamp
}

// Request to write a product.
message WriteProductRequest {
  Product product = 1; // Product to be written
}

// Response for writing a product.
message WriteProductResponse {
  string id = 1; // ID of the created product (auto-generated by the database)
}

// Request to update a product.
message UpdateProductRequest {
  string id = 1; // ID of the product to update
  Product product = 2; // Updated product data
}

// Response for updating a product.
message UpdateProductResponse {
  bool success = 1; // Indicates whether the update was successful
}

// Request to delete a product.
message DeleteProductRequest {
  string id = 1; // ID of the product to delete
}

// Response for deleting a product.
message DeleteProductResponse {
  bool success = 1; // Indicates whether the deletion was successful
}

// Request to delete a product.
message RecoverProductRequest {
  string id = 1; // ID of the product to delete
}

// Response for deleting a product.
message RecoverProductResponse {
  bool success = 1; // Indicates whether the deletion was successful
}

// Represents a summary of a product.
message Summary {
  string id = 1; // Unique identifier for the product
  string name = 2; // Name of the product
  string thumbnail_url = 3; // URL of the thumbnail image
  string category_name = 4; // Name of the category
  uint32 cent_price = 5; // Price in cents (e.g., 5000 for $50.00)
  bool in_stock = 6; // Availability status
  float rating = 7; // Product rating (e.g., 4.5)
  uint32 amount_sold = 8; // Number of units sold
  google.protobuf.Timestamp created_at = 9; // Database timestamp
}

// Request to list products.
message ListSummariesRequest {

}

// Response for listing products (streamed).
message ListSummariesResponse {
  repeated Summary products = 1; // List of product summaries in this chunk
}

// Request to get product details.
message GetDetailRequest {
  string id = 1; // ID of the product to fetch
}

// Response for getting product details.
message Detail {
  string id = 1; // ID of the product
  string name = 2; // Name of the product
  string category_name = 3; // Name of the category
  string description = 4; // Description of the product
  uint32 cent_price = 5; // Price in cents (e.g., 5000 for $50.00)
  float rating = 6; // Product rating (e.g., 4.5)
  GalleryOption gallery_option = 7; // Gallery option (e.g., color with images)
  repeated Option options = 8; // option List (e.g., size, material)
  google.protobuf.Struct attributes = 9; // size chart, material, etc. 
  google.protobuf.Timestamp created_at = 10; // Database timestamp
}

// Request to list categories.
message ListCategoriesRequest {

}

// Response for listing categories (streamed).
message ListCategoriesResponse {
  repeated string categories = 1; // List of category names in this chunk
}

message ListProductsRequest {

}

message ListProductsResponse {
  repeated Product products = 1;
}

// Service for reading product data with streaming support.
service ProductReadService {
  rpc ListProducts(ListProductsRequest) returns (ListProductsResponse);
  rpc ListCategories(ListCategoriesRequest) returns (ListCategoriesResponse);
  rpc ListSummaries(ListSummariesRequest) returns (ListSummariesResponse);
  rpc GetDetails(GetDetailRequest) returns (Detail);
}

// Service for writing, updating, and deleting products.
service ProductWriteService {
  rpc WriteProduct(WriteProductRequest) returns (WriteProductResponse);
  rpc UpdateProduct(UpdateProductRequest) returns (UpdateProductResponse);
  rpc DeleteProduct(DeleteProductRequest) returns (DeleteProductResponse);
  rpc RecoverProduct(RecoverProductRequest) returns (RecoverProductResponse);
}